# Generated by Django 4.2.2 on 2023-06-11 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_usermessage'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMessage',
        ),
    ]
