# Generated by Django 4.2.2 on 2023-06-12 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_message_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='reported',
            field=models.BooleanField(default=False),
        ),
    ]
